name: 'Newman Action (version with apiBase)'
description: 'testing newman and github' 
author: 'Gasparhe'
branding:
  icon: 'check-square'
  color: 'orange'
inputs:
  collection:
    description: 'Collection to use'
    required: true
  environment:
    description: 'Environment to use'
    required: true
  apiKey:
    description: 'Postman API key'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
