name: 'Newman - Postman.'
description: 'Run a private Postman collection. This is a fork of https://github.com/matt-ball/newman-action' 
author: 'gasparhe'
branding:
  icon: 'list'
  color: 'yellow'
inputs:
  collection:
    description: 'Collection ID to use'
    required: true
  environment:
    description: 'Environment ID to use'
    required: true
  apiKey:
    description: 'Postman API key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
